#!/usr/bin/env sh
#
# Collect the AWS managed domain lists of Route53 Resolver DNS Firewall for every
# region and write them to `managed-domain-lists.yaml`.
#
# The ID of a managed domain list differs by region and neither AWS nor the
# Terraform provider offers a way to look one up by name, so the module resolves
# the ID from the generated file.
#
# Usage:
#   ./get-managed-domain-lists.sh
#   REGIONS="us-east-1 ap-northeast-2" ./get-managed-domain-lists.sh
#   OUTPUT=/tmp/lists.yaml ./get-managed-domain-lists.sh
#
# Requires `aws`, `jq` and `yq`. Regions which the caller cannot reach - a
# disabled opt-in region, or one without DNS Firewall - are skipped.

set -eu

OUTPUT="${OUTPUT:-managed-domain-lists.yaml}"
REGIONS="${REGIONS:-$(aws ec2 describe-regions \
  --all-regions \
  --query 'Regions[].RegionName' \
  --output text)}"

RAW="$(mktemp)"
trap 'rm -f "$RAW"' EXIT

for region in ${REGIONS}; do
  printf '==> %s' "${region}" >&2

  if ! response="$(aws route53resolver list-firewall-domain-lists \
    --region "${region}" \
    --output json \
    2>/dev/null)"; then
    printf ' - skipped\n' >&2
    continue
  fi

  printf '\n' >&2
  printf '%s' "${response}" \
    | jq --arg region "${region}" '
      [
        .FirewallDomainLists[]
        | select(.ManagedOwnerName != null)
        | {
          key: .Name,
          value: .Id,
        }
      ]
      | if length == 0
        then empty
        else { ($region): (sort_by(.key) | from_entries) }
        end
    ' >> "${RAW}"
done

{
  echo '# This file is generated by `get-managed-domain-lists.sh`. DO NOT EDIT.'
  echo '#'
  echo '# The IDs of the AWS managed domain lists of Route53 Resolver DNS Firewall,'
  echo '# keyed by the region and then by the name of the domain list.'
  jq -s 'add // {}' "${RAW}" \
    | yq --input-format json --output-format yaml 'sort_keys(..)'
} > "${OUTPUT}"

printf 'Wrote %s\n' "${OUTPUT}" >&2
