version: 2
updates:
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: daily

- package-ecosystem: terraform
  directories:
  - /modules/dns-firewall
  - /modules/dns-firewall-domain-list
  - /modules/dns-firewall-rule-group
  - /modules/fms-dns-firewall-policy
  - /modules/waf-ip-set
  schedule:
    interval: weekly
