# Warning
- color: "ee0701"
  description: "Categorize bug reports."
  name: ":warning: bug"
- color: "ee0701"
  description: "Categorize vulnerability reports."
  name: ":warning: vulnerability"

# Highlight
- color: "0e8a16"
  description: "Good for newcomers."
  name: ":fire: good first issue"
- color: "0e8a16"
  description: "Extra attention is needed."
  name: ":fire: help wanted"
# Cancel
- color: "b60205"
  description: "This issue or pull request already exists."
  name: ":pray: duplicate"
- color: "b60205"
  description: "This will not be worked on."
  name: ":pray: wontfix"

# Size
- color: "cfd3d7"
  description: "Extra Small size issue or PR."
  name: "size/XS"
- color: "cfd3d7"
  description: "Small size issue or PR."
  name: "size/S"
- color: "cfd3d7"
  description: "Medium size issue or PR."
  name: "size/M"
- color: "cfd3d7"
  description: "Large size issue or PR."
  name: "size/L"
- color: "cfd3d7"
  description: "Extra Large size issue or PR."
  name: "size/XL"

# Modules
- color: "fbca04"
  description: "This issue or pull request is related to dns-firewall-domain-list module."
  name: ":floppy_disk: dns-firewall-domain-list"
- color: "fbca04"
  description: "This issue or pull request is related to dns-firewall-rule-group module."
  name: ":floppy_disk: dns-firewall-rule-group"
- color: "fbca04"
  description: "This issue or pull request is related to dns-firewall module."
  name: ":floppy_disk: dns-firewall"
- color: "fbca04"
  description: "This issue or pull request is related to fms-dns-firewall-policy module."
  name: ":floppy_disk: fms-dns-firewall-policy"
- color: "fbca04"
  description: "This issue or pull request is related to network-firewall module."
  name: ":floppy_disk: network-firewall"
